name: CI Node.js

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  testar-api:

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: "Checkout do código"
      uses: actions/checkout@v4

    - name: "Configurar Node.js ${{ matrix.node-version }}"
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: "Instalar dependências"
      run: npm ci

    - name: "Iniciar servidor em segundo plano"
      run: |
        npm run startAPI &
        echo $! > server.pid
      shell: bash

    - name: "Aguardar o servidor iniciar"
      run: |
        echo "Aguardando o servidor..."
        for i in {1..30}; do
          # Usa curl para verificar se o endpoint /visitas está respondendo
          if curl -f http://localhost:3000/visitas 2>/dev/null; then
            echo "Servidor pronto!"
            exit 0
          fi
          sleep 1
        done
        echo "Erro: Servidor não iniciou em 30 segundos."
        exit 1
      shell: bash

    - name: "Executar testes com Jest"
      run: npm test

    - name: "Parar o servidor"
      if: always()
      run: |
        if [ -f server.pid ]; then
          kill $(cat server.pid)
        fi
      shell: bash